$('header').html(
  '   <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">'
  + '    <button class="m-2 navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"'
  + '        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">'
  + '        <span class="navbar-toggler-icon"></span>'
  + '    </button>'

  + '   <div class="container" style="width: 777px;">'
  + '    <div class="m-2 collapse navbar-collapse" id="navbarTogglerDemo02">'
  + '        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 nav-fill w-100">'
  + '            <li class="nav-item">'
  + '                <a class="nav-link" href="./index.html">Sobre</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link" href="./academico.html">Acadêmico</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link" href="./design.html">Design</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link disabled" href="">Moda</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link" href="./programacao.html">Programação</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link disabled" href="">Música</a>'
  + '            </li>'
  + '            <li class="nav-item">'
  + '                <a class="nav-link" href="./jiu_jitsu.html">Jiu-Jitsu</a>'
  + '            </li>'
  + '        </ul>'
  + '    </div>'
  + '</div>'
  + '</nav>');
